### ISSUE TITLE
Dockerfile does not load if args are used in the EXPOSE command

### ISSUE THREAD

**Issue by jbharrell** [gbevan/dockerfile-syntax-highlighter#1]
If ARGs are used in the EXPOSE command the file does not load.

i.e.

ARG port
EXPOSE ${port}

**Comment by gbevan** [comment]
Fixed in 1.0.1.  Please upgrade via Brackets Extension Manager.

**Comment by jbharrell** [comment]
Thanks for the quick turnaround!  Just tested out the fix and seems to work.
