### ISSUE TITLE
Can't install with npm install dockerfile-syntax-highlighter.

### ISSUE THREAD

**Issue by Shanky2304** [gbevan/dockerfile-syntax-highlighter#5]
I am using Visual Studio Code. I have node installed.

When I run `npm dockerfile-syntax-highlighter`. I get,

 ```
Error: Cannot find module 'C:\Users\shankarv\zvivek\AngularProjects\quickstart-master\node_modules\dockerfile-syntax-highlighter\node
_modules\.bin\jacob'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dockerfile-syntax-highlighter@1.0.5 install: `node node_modules/.bin/jacob -t Dockerfile.jacoblex -l dockerlex.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dockerfile-syntax-highlighter@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I have the required file `..\node_modules\.bin\jacob` but I don't understand why it tries to find
`\node_modules\dockerfile-syntax-highlighter\node_modules\.bin\jacob`

**Comment by gbevan** [comment]
Hi @Shanky2304 this extension was written to install into Brackets Editor and it's related project Brackets-Electron - the npm integration is for the brackets-npm-registry extension to allow this plugin to be installed and upgraded via the Brackets UI.

I don't use Visual Studio, so I have no idea if this will ever work for you.  Sorry.

You could try the `--ignore-scripts` option on the `npm install ...` to get past that error...
