### ISSUE TITLE
Not easily usable with light theme

### ISSUE THREAD

**Issue by OwensCode** [gbevan/dockerfile-syntax-highlighter#6]
Thanks for your work on this extension. The colors make it difficult to use with the Brackets Light theme; mostly the light blue / cyan.

![image](https://user-images.githubusercontent.com/7966269/42517672-4823f3c2-842e-11e8-8f58-4652de087f5b.png)

Is there a way to configure it to use different colors?

**Comment by gbevan** [comment]
hi @OwensCode , i'm actually using GitHub's Atom editor these days.  At some point I'd like to port this project to Atom - maybe I can add your requirement then for Atom.
Closing this for now as wont-do (sorry).
